# Generated by Django 2.2.19 on 2021-04-06 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officeAttender', '0002_auto_20210405_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='workspace',
            new_name='workspace_id',
        ),
    ]
