# Generated by Django 2.2.19 on 2021-04-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officeAttender', '0003_auto_20210406_0627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='workspace_id',
            new_name='workspace',
        ),
    ]
