# Generated by Django 2.2.19 on 2021-04-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeAttender', '0004_auto_20210406_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='isManagement',
            field=models.BooleanField(default=False),
        ),
    ]
