# Generated by Django 2.2.19 on 2021-04-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeAttender', '0005_auto_20210406_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
