# Generated by Django 2.2.19 on 2021-04-21 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officeAttender', '0012_auto_20210421_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='officeAttender.WorkSpace'),
            preserve_default=False,
        ),
    ]
